### ISSUE TITLE
Languages can't be sorted on language ui.

### ISSUE THREAD

**Issue by mibocs** [openeuropa/oe_multilingual#106]
On admin/config/regional/language page languages can’t be sorted. This means that we can’t have an abc order in the language switcher(frontend). In other word order of languages can't be exported to config.

It is because oe_multilingual_configurable_language_presave function prevent us to sort it. It restores the weight of the languages from web/modules/contrib/oe_multilingual/config/install directory.

web/modules/contrib/oe_multilingual/oe_multilingual.module:79
`function oe_multilingual_configurable_language_presave(EntityInterface $entity) {
  $storage = new FileStorage(drupal_get_path('module', 'oe_multilingual') . '/config/install');
  $values = $storage->read('language.entity.' . $entity->id());
  if ($values) {
    foreach ($values as $key => $value) {
      $entity->set($key, $value);
    }
  }
}`

Could you remove this function or somehow add and option to be optional? Thanks!

**Comment by richardcanoe** [comment]
Hi @mibocs The order of languages in this list is defined by https://publications.europa.eu/code/en/en-370200.htm
There are no plans to change it or make it optional.
